version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./resources
        target: /resources
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}

  database:
    build: 
      context: .
      dockerfile: ./infrastructure/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: database-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}

  application:
    build: 
      context: .
      dockerfile: ./infrastructure/php/application/Dockerfile
    volumes:
      - type: bind
        source: ./resources/application
        target: /resources/application
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

  dashboard:
    build: 
      context: .
      dockerfile: ./infrastructure/php/dashboard/Dockerfile
    volumes:
      - type: bind
        source: ./resources/dashboard
        target: /resources/dashboard
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

volumes:
  database-store:
  pma-session-store: